### ISSUE TITLE
Project won't build 

### ISSUE THREAD

**Issue by houstonhaynes** [WildernessLabs/Clima#2]
I'm getting Secrets and ConnectionStatus issues that confound me - I'm not sure why either is occurring as secrets are populated and present and the namespacing matches up. 

![image](https://user-images.githubusercontent.com/8174976/115573403-8fa8a680-a275-11eb-91e5-775ab5ed5068.png)

**Comment by houstonhaynes** [comment]
Sorry - secrets is both in "Pro" and in "HackKit" I was focused on HackKit - but this begs the questions of what are the distinctions - why do both need to exist. I'm pretty confused by this project now. And that seems counter-productive. (and still getting the ConnectionStatus errors)

**Comment by adrianstevens** [comment]
Hi @houstonhaynes - there was a little complexity with the secrets file to try and prevent people from checking in their WiFi credentials in the code.

We've simplified the secrets file for the hack kit project - it should build now without any modifications.

**Comment by houstonhaynes** [comment]
Thanks. I *did* begin to grok what's happening and look forward to checking the latest beta this week.

**Comment by adrianstevens** [comment]
fixed - closing
